class_name BattleConstants
extends RefCounted

enum Team { PLAYER, ENEMY }
enum UnitType { CHARACTER, PET }
enum Element { GOLD, WOOD, WATER, FIRE, EARTH, NONE }
enum SkillKind { PHYSICAL, SPELL, OBSTACLE, SUPPORT, ULTIMATE }
enum TargetRule { SINGLE_ENEMY, MULTI_ENEMY, SINGLE_ALLY, MULTI_ALLY, SELF, ALL_ENEMIES, ALL_ALLIES }
enum StatusKind { FORGET, POISON, FREEZE, SLEEP_LOCK, CONFUSION, ATTACK_UP, REGEN, DEFENSE_UP, SPEED_UP, DODGE_UP }
enum BattlePhase { START, WAITING_FOR_PLAYER_SKILL, WAITING_FOR_PLAYER_TARGET, ENEMY_ACTING, RESOLVING, FINISHED }
